# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: onurleiden
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: sns
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sns

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - sns:
          arn: arn:aws:sns:eu-west-3:199287124841:mySNSTopic  # Replace with your actual ARN
          displayName: My SNS Topic

resources:
  Resources:
    mySNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: mySNSTopic
 