# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: onurleiden
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: javascript-http-noexpress
# "service" is the name of this project. This will also be added to your AWS resource names.
service: javascript-http-noexpress

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
    
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
