service: aws-java-simple-http-endpoint
# frameworkVersion: '2'

provider:
  name: aws
  runtime: java21  # in previos experiment it was java 11 
  region: eu-west-3
package:
  artifact: build/distributions/aws-java-simple-http-endpoint.zip

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: /time
          method: get
