org: onurleiden
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: sns-chain
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sns-chain

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::mybucket-triggerbench-chain"
        - "arn:aws:s3:::mybucket-triggerbench-chain/*"

functions:
  hello:
    handler: handler.hello
    events:
      - sns:
          arn: arn:aws:sns:eu-west-3:199287124841:myChainTopic  # Updated ARN to use myChainTopic
          displayName: My Chain Topic  # Updated display name to match the new topic name

resources:
  Resources:
    myChainTopic:  # Updated resource name to match the new topic name
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: myChainTopic  # Updated topic name
