# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: onurleiden
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: http-chain
# "service" is the name of this project. This will also be added to your AWS resource names.
service: http-chain

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"

      Resource: 
      - "arn:aws:sns:eu-west-3:199287124841:myChainTopic"
      - "*"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
