# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: onurleiden
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: python-http
# "service" is the name of this project. This will also be added to your AWS resource names.
service: python-http

provider:
  name: aws
  runtime: python3.12
  region: eu-west-3
  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "logs:CreateLogGroup"
      - "logs:CreateLogStream"
      - "logs:PutLogEvents"
    Resource: "*"
    
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
